"use strict";
const fs=require("fs"),path=require("path"),http=require("http"),assert=require("assert");
const {chromium,webkit}=require("playwright");
const PUBLIC=path.join(__dirname,"public"),indexPad=path.join(PUBLIC,"index.html");
if(!fs.existsSync(indexPad))throw new Error("public/index.html ontbreekt.");
let html=fs.readFileSync(indexPad,"utf8");
html=html.replace("</head>",'<script>try{localStorage.removeItem("weerbriefing.thema")}catch(e){};window.fetch=async()=>({ok:false,status:503,json:async()=>({}),text:async()=>""});</script></head>');
const mime={".js":"application/javascript",".json":"application/json",".woff2":"font/woff2",".png":"image/png"};
const server=http.createServer((req,res)=>{const p=(req.url||"/").split("?")[0];if(p==="/"){res.writeHead(200,{"content-type":"text/html"});res.end(html);return;}const f=path.join(PUBLIC,p.replace(/^\//,""));if(f.startsWith(PUBLIC+path.sep)&&fs.existsSync(f)){res.writeHead(200,{"content-type":mime[path.extname(f)]||"application/octet-stream"});fs.createReadStream(f).pipe(res);return;}res.writeHead(404);res.end();});
async function check(type,naam,breedte){
  const browser=await type.launch({headless:true}),page=await browser.newPage({viewport:{width:breedte,height:900}}),errors=[];page.on("pageerror",e=>errors.push(String(e)));
  try{
    await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:"domcontentloaded"});
    await page.waitForSelector("#thema");
    await page.evaluate(()=>{ls.set("weerbriefing.thema","licht");themaToepassen();});
    const init=await page.evaluate(()=>{const k=document.getElementById("thema"),f=document.querySelector('link[rel="icon"]'),s=getComputedStyle(k),t=getComputedStyle(document.querySelector(".tools"));return {role:k.getAttribute("role"),checked:k.getAttribute("aria-checked"),keuze:k.dataset.actieveThemakeuze,actief:document.documentElement.dataset.thema,menu:!!document.getElementById("themamenu"),track:!!k.querySelector(".wiw-theme-track"),thumb:!!k.querySelector(".wiw-theme-thumb"),fav:f&&f.getAttribute("href"),past:k.scrollWidth<=k.clientWidth+1,clientWidth:k.clientWidth,scrollWidth:k.scrollWidth,fontSize:s.fontSize,fontFamily:s.fontFamily,letterSpacing:s.letterSpacing,paddingLeft:s.paddingLeft,paddingRight:s.paddingRight,toolsDisplay:t.display,toolsWidth:document.querySelector(".tools").clientWidth,childCount:k.children.length,innerHTML:k.innerHTML,label:k.getAttribute("aria-label"),title:k.getAttribute("title")};});
    assert.equal(init.role,"switch",naam+": Weergave is semantisch een switch");assert.equal(init.checked,"false",naam+": lichte stand heeft aria-checked=false");assert.equal(init.keuze,"licht",naam+": expliciete lichte keuze zichtbaar in runtime-status");assert.equal(init.actief,"licht",naam+": lichte keuze wordt gerenderd");assert.equal(init.menu,false,naam+": oud themamenu is verwijderd");assert(init.track&&init.thumb,naam+": switch-track en thumb aanwezig");assert.equal(init.childCount,4,naam+": switch bevat zon, track, maan en screenreaderlabel");assert(init.label&&init.title,naam+": switch heeft toegankelijke toestandstekst");assert(init.fav&&init.fav.startsWith("data:image/svg+xml,"),naam+": zon-favicon");assert(init.past,naam+": switch past op "+breedte+"px; layout="+JSON.stringify({clientWidth:init.clientWidth,scrollWidth:init.scrollWidth,fontSize:init.fontSize,fontFamily:init.fontFamily,letterSpacing:init.letterSpacing,paddingLeft:init.paddingLeft,paddingRight:init.paddingRight,childCount:init.childCount,innerHTML:init.innerHTML,toolsDisplay:init.toolsDisplay,toolsWidth:init.toolsWidth}));
    await page.click("#thema");
    const donker=await page.evaluate(()=>({thema:document.documentElement.dataset.thema,keuze:document.getElementById("thema").dataset.actieveThemakeuze,checked:document.getElementById("thema").getAttribute("aria-checked"),opgeslagen:ls.get("weerbriefing.thema",""),actiefBewaar:ls.get("weerbriefing.actiefThema",""),ink45:getComputedStyle(document.documentElement).getPropertyValue("--ink-45").trim(),ink25:getComputedStyle(document.documentElement).getPropertyValue("--ink-25").trim()}));
    assert.deepEqual(donker,{thema:"donker",keuze:"donker",checked:"true",opgeslagen:"donker",actiefBewaar:"donker",ink45:"#A8A8A8",ink25:"#959595"},naam+": switch selecteert en bewaart donker met sterker secundair contrast");
    await page.click("#thema");
    const licht=await page.evaluate(()=>({thema:document.documentElement.dataset.thema,keuze:document.getElementById("thema").dataset.actieveThemakeuze,checked:document.getElementById("thema").getAttribute("aria-checked"),opgeslagen:ls.get("weerbriefing.thema","")}));
    assert.deepEqual(licht,{thema:"licht",keuze:"licht",checked:"false",opgeslagen:"licht"},naam+": tweede klik schakelt terug naar licht en bewaart die keuze");
    const oudRood=await page.evaluate(()=>{ls.set("weerbriefing.thema","rood");S.d={current:{is_day:0}};themaToepassen();const k=document.getElementById("thema");return {opgeslagen:ls.get("weerbriefing.thema",""),actief:document.documentElement.dataset.thema,keuze:k.dataset.actieveThemakeuze,checked:k.getAttribute("aria-checked"),roodOptie:!!document.querySelector('[data-thema-keuze="rood"]'),menu:!!document.getElementById("themamenu")};});
    assert.deepEqual(oudRood,{opgeslagen:"auto",actief:"donker",keuze:"auto",checked:"true",roodOptie:false,menu:false},naam+": oude rode voorkeur migreert veilig naar auto zonder oud menu");
    assert.deepEqual(errors,[],naam+": geen page errors");
  }finally{await browser.close();}
}
server.listen(0,"127.0.0.1",async()=>{try{for(const [t,n] of [[chromium,"Chromium"],[webkit,"WebKit"]]){await check(t,n,390);await check(t,n,1280);}console.log("UI-shell browsercontrole groen in Chromium en WebKit met licht/donker-switch.");}catch(e){console.error(e.stack||e);process.exitCode=1;}finally{server.close();}});
