"use strict";
const fs=require("fs"),path=require("path"),http=require("http"),assert=require("assert");
const {chromium,webkit}=require("playwright");
const PUBLIC=path.join(__dirname,"public"),indexPad=path.join(PUBLIC,"index.html");
if(!fs.existsSync(indexPad))throw new Error("public/index.html ontbreekt.");
let html=fs.readFileSync(indexPad,"utf8");
html=html.replace("</head>",'<script>try{localStorage.removeItem("weerbriefing.thema")}catch(e){};window.fetch=async()=>({ok:false,status:503,json:async()=>({}),text:async()=>""});</script></head>');
const mime={".js":"application/javascript",".json":"application/json",".woff2":"font/woff2",".png":"image/png"};
const server=http.createServer((req,res)=>{const p=(req.url||"/").split("?")[0];if(p==="/"){res.writeHead(200,{"content-type":"text/html"});res.end(html);return;}const f=path.join(PUBLIC,p.replace(/^\//,""));if(f.startsWith(PUBLIC+path.sep)&&fs.existsSync(f)){res.writeHead(200,{"content-type":mime[path.extname(f)]||"application/octet-stream"});fs.createReadStream(f).pipe(res);return;}res.writeHead(404);res.end();});
async function check(type,naam,breedte){
  const browser=await type.launch({headless:true}),page=await browser.newPage({viewport:{width:breedte,height:900}}),errors=[];page.on("pageerror",e=>errors.push(String(e)));
  try{
    await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:"domcontentloaded"});
    await page.waitForSelector("#thema");
    await page.evaluate(()=>{ls.set("weerbriefing.thema","licht");themaToepassen();});
    const init=await page.evaluate(()=>{const k=document.getElementById("thema"),m=document.getElementById("themamenu"),f=document.querySelector('link[rel="icon"]'),s=getComputedStyle(k),t=getComputedStyle(document.querySelector(".tools"));return {role:k.getAttribute("role"),popup:k.getAttribute("aria-haspopup"),expanded:k.getAttribute("aria-expanded"),keuze:k.dataset.actieveThemakeuze,actief:document.documentElement.dataset.thema,menu:!!m,menuHidden:m&&m.hidden,opties:m?m.querySelectorAll("[data-thema-keuze]").length:0,lichtChecked:m&&m.querySelector('[data-thema-keuze="licht"]')?.getAttribute("aria-checked"),track:!!k.querySelector(".wiw-theme-track"),thumb:!!k.querySelector(".wiw-theme-thumb"),status:!!k.querySelector(".thema-status"),fav:f&&f.getAttribute("href"),past:k.scrollWidth<=k.clientWidth+1,clientWidth:k.clientWidth,scrollWidth:k.scrollWidth,fontSize:s.fontSize,fontFamily:s.fontFamily,letterSpacing:s.letterSpacing,paddingLeft:s.paddingLeft,paddingRight:s.paddingRight,toolsDisplay:t.display,toolsWidth:document.querySelector(".tools").clientWidth,childCount:k.children.length,innerHTML:k.innerHTML,label:k.getAttribute("aria-label"),title:k.getAttribute("title")};});
    assert.equal(init.role,null,naam+": Weergave gebruikt geen binaire switchrol op een weatherpagina");assert.equal(init.popup,"menu",naam+": Weergave kondigt het keuzemenu aan");assert.equal(init.expanded,"false",naam+": Weergavemenu is initieel gesloten");assert.equal(init.keuze,"licht",naam+": expliciete lichte keuze zichtbaar in runtime-status");assert.equal(init.actief,"licht",naam+": lichte keuze wordt gerenderd");assert.equal(init.menu,true,naam+": Auto/Licht/Donker-menu is aanwezig");assert.equal(init.menuHidden,true,naam+": Weergavemenu is initieel verborgen");assert.equal(init.opties,3,naam+": Weergavemenu bevat exact Auto, Licht en Donker");assert.equal(init.lichtChecked,"true",naam+": Licht is als actuele keuze gemarkeerd");assert(!init.track&&!init.thumb,naam+": verouderde binaire switch-track en thumb ontbreken");assert(init.status,naam+": compacte themastatus is aanwezig");assert(init.label&&init.title,naam+": Weergaveknop heeft toegankelijke toestandstekst");assert(init.fav&&init.fav.startsWith("data:image/svg+xml,"),naam+": zon-favicon");assert(init.past,naam+": Weergaveknop past op "+breedte+"px; layout="+JSON.stringify({clientWidth:init.clientWidth,scrollWidth:init.scrollWidth,fontSize:init.fontSize,fontFamily:init.fontFamily,letterSpacing:init.letterSpacing,paddingLeft:init.paddingLeft,paddingRight:init.paddingRight,childCount:init.childCount,innerHTML:init.innerHTML,toolsDisplay:init.toolsDisplay,toolsWidth:init.toolsWidth}));
    await page.click("#thema");
    assert.equal(await page.getAttribute("#thema","aria-expanded"),"true",naam+": klik opent het Weergavemenu");
    await page.click('#themamenu [data-thema-keuze="donker"]');
    const donker=await page.evaluate(()=>{const k=document.getElementById("thema"),m=document.getElementById("themamenu");return {thema:document.documentElement.dataset.thema,keuze:k.dataset.actieveThemakeuze,expanded:k.getAttribute("aria-expanded"),donkerChecked:m.querySelector('[data-thema-keuze="donker"]').getAttribute("aria-checked"),opgeslagen:ls.get("weerbriefing.thema",""),actiefBewaar:ls.get("weerbriefing.actiefThema",""),ink45:getComputedStyle(document.documentElement).getPropertyValue("--ink-45").trim(),ink25:getComputedStyle(document.documentElement).getPropertyValue("--ink-25").trim()};});
    assert.deepEqual(donker,{thema:"donker",keuze:"donker",expanded:"false",donkerChecked:"true",opgeslagen:"donker",actiefBewaar:"donker",ink45:"#A8A8A8",ink25:"#959595"},naam+": menu selecteert en bewaart Donker met sterker secundair contrast");
    await page.click("#thema");
    await page.click('#themamenu [data-thema-keuze="licht"]');
    const licht=await page.evaluate(()=>{const k=document.getElementById("thema"),m=document.getElementById("themamenu");return {thema:document.documentElement.dataset.thema,keuze:k.dataset.actieveThemakeuze,expanded:k.getAttribute("aria-expanded"),lichtChecked:m.querySelector('[data-thema-keuze="licht"]').getAttribute("aria-checked"),opgeslagen:ls.get("weerbriefing.thema","")};});
    assert.deepEqual(licht,{thema:"licht",keuze:"licht",expanded:"false",lichtChecked:"true",opgeslagen:"licht"},naam+": menu schakelt terug naar Licht en bewaart die keuze");
    const oudRood=await page.evaluate(()=>{ls.set("weerbriefing.thema","rood");S.d={current:{is_day:0}};themaToepassen();const k=document.getElementById("thema"),m=document.getElementById("themamenu");return {opgeslagen:ls.get("weerbriefing.thema",""),actief:document.documentElement.dataset.thema,actiefBewaar:ls.get("weerbriefing.actiefThema",""),keuze:k.dataset.actieveThemakeuze,expanded:k.getAttribute("aria-expanded"),autoChecked:m.querySelector('[data-thema-keuze="auto"]').getAttribute("aria-checked"),roodOptie:!!m.querySelector('[data-thema-keuze="rood"]'),menu:!!m};});
    assert.deepEqual(oudRood,{opgeslagen:"auto",actief:"donker",actiefBewaar:"donker",keuze:"auto",expanded:"false",autoChecked:"true",roodOptie:false,menu:true},naam+": oude rode voorkeur migreert veilig naar Auto met providerfallback en zonder rode optie");
    assert.deepEqual(errors,[],naam+": geen page errors");
  }finally{await browser.close();}
}
server.listen(0,"127.0.0.1",async()=>{try{for(const [t,n] of [[chromium,"Chromium"],[webkit,"WebKit"]]){await check(t,n,390);await check(t,n,1280);}console.log("UI-shell browsercontrole groen in Chromium en WebKit met canoniek Auto/Licht/Donker-menu.");}catch(e){console.error(e.stack||e);process.exitCode=1;}finally{server.close();}});
