"use strict";
const fs=require("fs"),os=require("os"),path=require("path"),crypto=require("crypto"),{spawnSync}=require("child_process");
function vindBrowser(){for(const n of ["google-chrome","google-chrome-stable","chromium","chromium-browser"]){const r=spawnSync("sh",["-lc","command -v "+n],{encoding:"utf8"});if(r.status===0&&r.stdout.trim())return r.stdout.trim();}return null;}
const browser=vindBrowser();if(!browser){if(process.env.CI){console.error("FOUT finale desktop-UI browsertest: Chrome/Chromium ontbreekt.");process.exit(1);}console.log("SKIP finale desktop-UI browsertest: lokaal geen Chrome/Chromium.");process.exit(0);}
const productie=path.join(__dirname,"public","index.html");if(!fs.existsSync(productie))throw new Error("public/index.html ontbreekt.");
let html=fs.readFileSync(productie,"utf8");
const stub=`<script>try{localStorage.clear();sessionStorage.clear();}catch(e){}window.fetch=()=>new Promise(()=>{});window.requestAnimationFrame=callback=>setTimeout(()=>callback(performance.now()),16);window.cancelAnimationFrame=clearTimeout;try{Object.defineProperty(navigator,'geolocation',{value:undefined,configurable:true});}catch(e){}</script>`;html=html.replace("</head>",stub+"</head>");
const reporter=`<script>
setTimeout(async()=>{const zet=(k,v)=>document.body.setAttribute('data-final-desktop-'+k,String(v));try{
 document.documentElement.classList.remove('wn-progressief');const app=document.getElementById('app');if(app){app.classList.remove('wn-progressief');app.removeAttribute('aria-busy');app.style.display='block';}const state=document.getElementById('state');if(state)state.style.display='none';
 const TI=Array.from({length:24},(_,i)=>i<11?'2026-09-02T'+String(i+13).padStart(2,'0')+':00':'2026-09-03T'+String(i-11).padStart(2,'0')+':00');
 S.d={timezone:'Europe/Amsterdam',utc_offset_seconds:7200,current:{time:'2026-09-02T13:27'},hourly:{time:TI,temperature_2m:TI.map((_,i)=>-8.5+i*.7),apparent_temperature:TI.map((_,i)=>-14.2+i*.55),precipitation_probability:TI.map((_,i)=>10+i),precipitation:TI.map((_,i)=>i/10)}};S.klokInstantOverride=new Date('2026-09-02T11:27:00Z');S.geo={TI,T:S.d.hourly.temperature_2m,A:S.d.hourly.apparent_temperature};S.dag=null;
 let fake=[...document.querySelectorAll('details')].find(d=>/grafiekgegevens.*tabel/i.test(d.querySelector('summary')?.textContent||''));if(!fake){fake=document.createElement('details');const s=document.createElement('summary');s.textContent='Grafiekgegevens als tabel';fake.appendChild(s);fake.appendChild(document.createElement('table'));document.querySelector('.dagmod')?.appendChild(fake);}
 WeatherNowFinalDesktopUI20260902.render();
 await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
 const width=innerWidth,desktop=width>=1100,grid=document.getElementById('wiw-chart-layout'),main=grid?.querySelector('.wiw-chart-main'),hour=document.getElementById('wiw-hour-panel');
 const rr=e=>{const r=e?.getBoundingClientRect();return r?{l:r.left,r:r.right,t:r.top,b:r.bottom,w:r.width,h:r.height}:null;},gm=rr(main),gh=rr(hour);
 const stats=[...document.querySelectorAll('.final-top-grid>.stats .stat')].filter(e=>getComputedStyle(e).display!=='none'),st=stats.map(e=>getComputedStyle(e));
 zet('pressure-visible',!!document.getElementById('wiw-more-measurements'));zet('pressure-hidden',document.getElementById('pres')?.closest('#wiw-pressure-diagnostic')?'ok':'fout');
 zet('tiles',stats.length);zet('tiles-centered',st.every(s=>s.textAlign==='center'&&s.alignItems==='center'&&s.justifyContent==='center')?'ok':'fout');
 zet('rows',document.querySelectorAll('#wiw-hour-table tbody tr').length);zet('scopes',[...document.querySelectorAll('#wiw-hour-table th')].filter(th=>th.getAttribute('scope')==='col').length);zet('headers',[...document.querySelectorAll('#wiw-hour-table thead th')].map(th=>th.textContent.trim()).join('|'));zet('row-shape',[...document.querySelectorAll('#wiw-hour-table tbody tr')].every(tr=>tr.children.length===4&&/%$/.test(tr.children[2].textContent.trim())&&/mm$/.test(tr.children[3].textContent.trim()))?'ok':'fout');zet('tabindex',document.getElementById('wiw-hour-scroll')?.tabIndex);zet('current',document.querySelectorAll('#wiw-hour-table tr[data-current="1"]').length);zet('marker',document.querySelector('#wiw-hour-table tr[data-current="1"] .wiw-hour-marker')?.textContent||'');
 zet('button',document.getElementById('wiw-all-data-button')?'aanwezig':'absent');const rainSection=document.getElementById('wiw-rain-section');zet('rain-visible',rainSection&&rainSection.getClientRects().length?'visible':'hidden');zet('chart-data-visible',[...document.querySelectorAll('details')].some(d=>/grafiekgegevens.*tabel/i.test(d.querySelector('summary')?.textContent||'')&&d.getClientRects().length)?'visible':'hidden');zet('hint-center',getComputedStyle(document.getElementById('charthint')).textAlign);
 if(desktop){zet('chart-cols',gm&&gh&&gh.l>gm.l+gm.w*.8?'2':'fout');zet('chart-ratio',gm&&gh?(gm.w/(gm.w+gh.w)).toFixed(2):'0');zet('chart-height',gm&&gh?Math.abs(gm.h-gh.h)<=3?'ok':'fout');}
 else{zet('chart-cols',gm&&gh&&gh.t>=gm.b-2?'stack':'fout');}zet('rain-cols','hidden');
 const footer=document.querySelector('footer'),nav=document.querySelector('.seo-plaatsnav');zet('footer-height',Math.round(footer?.getBoundingClientRect().height||0));zet('nav-height',Math.round(nav?.getBoundingClientRect().height||0));zet('overflow',Math.round(Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)-innerWidth));zet('done','ok');
}catch(e){zet('exception',e&&e.stack||e);zet('done','fout');}},250);
</script>`;html=html.replace("</body>",reporter+"</body>");
const dir=fs.mkdtempSync(path.join(os.tmpdir(),"wiw-final-desktop-"));
try{const pad=path.join(dir,"index.html");fs.writeFileSync(pad,html);for(const [w,h] of [[320,900],[390,900],[430,932],[1024,900],[1366,768],[1440,900],[1920,1080]]){const args=["--headless=new","--no-sandbox","--disable-gpu","--disable-dev-shm-usage","--allow-file-access-from-files",`--window-size=${w},${h}`,"--virtual-time-budget=1000","--dump-dom","file://"+pad];const r=spawnSync(browser,args,{encoding:"utf8",maxBuffer:36*1024*1024});if(r.status!==0)throw new Error(`${w}px: browser exit ${r.status}: `+String(r.stderr||"").slice(-800));const dom=r.stdout||"",v=k=>{const m=new RegExp('data-final-desktop-'+k+'="([^"]*)"').exec(dom);return m&&m[1];};if(v('done')!=='ok')throw new Error(`${w}px reporter: ${v('exception')}`);if(v('pressure-visible')!=='false'||v('pressure-hidden')!=='ok')throw new Error(`${w}px: zichtbare luchtdruk niet volledig verwijderd`);if(v('tiles')!=='8'||v('tiles-centered')!=='ok')throw new Error(`${w}px: acht gecentreerde hoofdtegels niet geborgd`);if(v('scopes')!=='4'||v('button')!=='absent'||v('headers')!=='Tijd|Temperatuur|Kans|Neerslag'||v('row-shape')!=='ok'||v('rain-visible')!=='hidden'||v('chart-data-visible')!=='hidden'||(w>=1100?!(Number(v('rows'))>=1&&Number(v('rows'))<=10&&v('tabindex')==='-1'&&v('current')==='0'&&v('marker')===''):(v('rows')!=='24'||v('tabindex')==='0'||v('current')==='1'||v('marker')==='Eerstvolgend')))throw new Error(`${w}px: uur/neerslag UI fout rows=${v('rows')} scopes=${v('scopes')} headers=${v('headers')} rain=${v('rain-visible')} button=${v('button')}`);if(v('hint-center')!=='center')throw new Error(`${w}px: korte grafiekhint niet gecentreerd`);if(w>=1100){if(v('chart-cols')!=='2'||v('rain-cols')!=='hidden'||v('chart-height')!=='ok')throw new Error(`${w}px: desktopkolom/hoogte of verborgen neerslagblok fout`);const ratio=Number(v('chart-ratio'));if(!(ratio>=.62&&ratio<=.74))throw new Error(`${w}px: grafiekaandeel ${ratio} buiten rustige 62–74% band`);if(Number(v('footer-height'))>105)throw new Error(`${w}px: footer te hoog (${v('footer-height')}px)`);if(Number(v('nav-height'))>110)throw new Error(`${w}px: populaire-plaatsenstrook te hoog (${v('nav-height')}px)`);}else if(v('chart-cols')!=='stack'||v('rain-cols')!=='hidden')throw new Error(`${w}px: responsive stacking of verborgen neerslagblok fout`);if(Number(v('overflow'))>2)throw new Error(`${w}px: ${v('overflow')}px horizontale overflow`);
 if(w===390||w===1920){const png=path.join(dir,`final-desktop-ui-${w}.png`);const shot=spawnSync(browser,["--headless=new","--no-sandbox","--disable-gpu","--disable-dev-shm-usage","--allow-file-access-from-files",`--window-size=${w},${h}`,"--virtual-time-budget=1000","--screenshot="+png,"--hide-scrollbars","file://"+pad],{encoding:"utf8"});if(shot.status===0&&fs.existsSync(png)){const hash=crypto.createHash('sha256').update(fs.readFileSync(png)).digest('hex').slice(0,12);console.log(`${w}px screenshot sha256 ${hash}`);}}
 console.log(`${w}px: finale desktop-UI groen; ${v('chart-cols')} grafiek, ${v('rain-cols')} neerslag, ${v('rows')} uur, overflow ${v('overflow')}px.`);}console.log("Finale desktop-UI browsertest geslaagd op 320/390/430/1024/1366/1440/1920 px.");}finally{fs.rmSync(dir,{recursive:true,force:true});}
