"use strict";
const fs=require("fs"),os=require("os"),path=require("path"),{spawnSync}=require("child_process"),{bouw}=require("../data.js");
function browser(){for(const n of ["google-chrome","google-chrome-stable","chromium","chromium-browser"]){const r=spawnSync("sh",["-lc","command -v "+n],{encoding:"utf8"});if(r.status===0&&r.stdout.trim())return r.stdout.trim();}return null;}
const chrome=browser();if(!chrome){if(process.env.CI)throw new Error("Chrome/Chromium ontbreekt voor delivery-startup-gate.");console.log("SKIP delivery-startup-gate: lokaal geen Chrome/Chromium.");process.exit(0);}
const root=path.join(__dirname,".."),publicDir=path.join(root,"public"),bron=fs.readFileSync(path.join(publicDir,"index.html"),"utf8");
if(!/weather-delivery/.test(bron)||!/<script src="\/app-[0-9a-f]{12}\.min\.js" defer><\/script>/.test(bron))throw new Error("Delivery-startup-gate verwacht het definitieve external-minified artifact.");
const d=bouw({tempNu:17,wcNu:1,ccNu:30,pp:()=>22,som:2.4});d.latitude=52.3676;d.longitude=4.9041;d.timezone="Europe/Amsterdam";d.utc_offset_seconds=7200;d.daily.sunshine_duration=d.daily.time.map(()=>7*3600);
const lucht={current:{european_aqi:24,us_aqi:40},hourly:{time:[d.current.time],alder_pollen:[0],birch_pollen:[0],grass_pollen:[2],mugwort_pollen:[0],ragweed_pollen:[0],olive_pollen:[0]}};
const vroeg=`<script>window.__deliveryErrors=[];addEventListener('error',e=>window.__deliveryErrors.push('error: '+(e.message||e.error||'onbekend')));addEventListener('unhandledrejection',e=>window.__deliveryErrors.push('rejection: '+String(e.reason&&e.reason.stack||e.reason||'onbekend')));window.fetch=async function(url){const u=String(url),payload=u.includes('/api/waarschuwingen')?${JSON.stringify({bron:"test",dekking:true,land:"NL",lijst:[]})}:u.includes('/api/neerslag')?${JSON.stringify({beschikbaar:false,provider:"knmi",reden:"niet beschikbaar"})}:u.includes('/api/luchtkwaliteit')?${JSON.stringify({beschikbaar:false,provider:"luchtmeetnet",reden:"niet beschikbaar"})}:u.includes('air-quality-api.open-meteo.com')?${JSON.stringify(lucht)}:u.includes('geocoding-api.open-meteo.com')?${JSON.stringify({results:[{name:"Amsterdam",latitude:52.3676,longitude:4.9041,admin1:"Noord-Holland",country_code:"NL"}]})}:u.includes('/api/plaatsnaam')?${JSON.stringify({naam:"Amsterdam",land:"NL",bron:"test"})}:${JSON.stringify(d)};return {ok:true,status:200,json:async()=>payload,text:async()=>JSON.stringify(payload),headers:{get:()=>null}};};try{Object.defineProperty(navigator,'geolocation',{value:undefined,configurable:true});}catch(e){}</script>`;
const rapport=`<script>setTimeout(()=>{const app=document.getElementById('app'),state=document.getElementById('state');document.body.setAttribute('data-delivery-app',app&&getComputedStyle(app).display!=='none'?'visible':'hidden');document.body.setAttribute('data-delivery-state',String(state&&state.textContent||'').replace(/\s+/g,' ').trim().slice(0,300));document.body.setAttribute('data-delivery-errors',(window.__deliveryErrors||[]).join(' | ').slice(0,1200));},2200);</script>`;
let html=bron.replace("</head>",vroeg+"</head>").replace("</body>",rapport+"</body>").replace(/src="\/(app-[0-9a-f]{12}\.min\.js)"/g,'src="./$1"');
const tmp=fs.mkdtempSync(path.join(publicDir,".delivery-startup-"));try{const pad=path.join(tmp,"index.html");fs.writeFileSync(pad,html);const r=spawnSync(chrome,["--headless=new","--no-sandbox","--disable-gpu","--disable-dev-shm-usage","--allow-file-access-from-files","--window-size=390,900","--virtual-time-budget=3200","--dump-dom","file://"+pad+"?lat=52.3676&lon=4.9041&plaats=Amsterdam&land=NL"],{encoding:"utf8",maxBuffer:32*1024*1024});if(r.status!==0)throw new Error("Delivery-startup Chrome exit "+r.status+": "+String(r.stderr||"").slice(-1200));const dom=r.stdout||"",veld=k=>{const m=new RegExp('data-delivery-'+k+'="([^"]*)"').exec(dom);return m?m[1].replace(/&quot;/g,'"').replace(/&amp;/g,'&'):"";};const app=veld("app"),state=veld("state"),errors=veld("errors");if(app!=="visible")throw new Error(`Delivery-startup faalde: app=${app||"onbekend"}; state=${state||"leeg"}; errors=${errors||"geen geregistreerde browserfout"}`);if(errors)throw new Error("Delivery-startup browserfouten: "+errors);console.log("Delivery-startup-gate groen: minified externe runtime start normaal, app zichtbaar en geen browserfouten.");}finally{fs.rmSync(tmp,{recursive:true,force:true});}
