"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const runtime=fs.readFileSync(path.join(__dirname,"ui-polish-20260813-runtime.js"),"utf8");
const apply=fs.readFileSync(path.join(__dirname,"apply-ui-polish-20260813.js"),"utf8");
const context={};vm.createContext(context);vm.runInContext(runtime,context);
const api=context.WeatherNowUiPolish20260813;
assert(api,"UI-polish helpercontract ontbreekt");

assert.equal(api.briefingBronSemantiek("Vandaag was het rond 13:00 het warmst, met <b>29 graden</b>."),"Het verwachte maximum lag vandaag rond 13:00 op <b>29 graden</b>.");
assert.equal(api.briefingBronSemantiek("Vandaag wordt het rond 14:00 het warmst, met maximaal <b>24 graden</b>."),"Het verwachte maximum ligt vandaag rond 14:00 op <b>24 graden</b>.");
assert.equal(api.briefingBronSemantiek("Morgen wordt het rond 15:00 het warmst, met maximaal <b>21&nbsp;graden</b>."),"Het verwachte maximum ligt morgen rond 15:00 op <b>21&nbsp;graden</b>.");
assert.equal(api.regenperiodeDagprefix("2026-08-17","2026-08-16"),"ma ");
assert.equal(api.regenperiodeDagprefix("2026-08-16","2026-08-16"),"");
const briefing="Vandaag wordt het warm. Vannacht koelt het af naar <b>16 graden</b>.";
assert.equal(api.briefingTijdtaal(briefing,"2026-08-16T00:03",19),"Vandaag wordt het warm. Later vannacht koelt het af naar <b>16 graden</b>.");
assert.equal(api.briefingTijdtaal(briefing,"2026-08-16T04:59",19),"Vandaag wordt het warm. Later vannacht koelt het af naar <b>16 graden</b>.");
assert.equal(api.briefingTijdtaal(briefing,"2026-08-16T04:28",16),"Vandaag wordt het warm. De minimumtemperatuur vannacht ligt rond <b>16 graden</b>.");
assert.equal(api.briefingTijdtaal(briefing,"2026-08-16T04:28",15.5),"Vandaag wordt het warm. De minimumtemperatuur vannacht ligt rond <b>16 graden</b>.");
assert.equal(api.briefingTijdtaal(briefing,"2026-08-16T05:00",19),briefing);
assert.equal(api.briefingTijdtaal(briefing,"2026-08-15T23:30",19),briefing);
assert.equal(api.dagNeerslagTekst(2,0),"Droog");
assert.equal(api.dagNeerslagTekst(9,0.05),"Droog");
assert.equal(api.dagNeerslagTekst(5,0.2),"5%");
assert.equal(api.isNwsStructuur("* WHAT...Heat index values. * WHERE...Dallas."),true);
assert.equal(api.isNwsStructuur("Plaatselijk zware buien mogelijk."),false);

assert.equal(api.uvPiekTekst,undefined);
assert(!runtime.includes("uiUvOordeel")&&!runtime.includes("uiUvPiekTekst")&&!runtime.includes('piek("uv_index")'));
assert.equal(api.pollenTekst,undefined);
assert(!runtime.includes("uiPollenTekst")&&!runtime.includes("uiPolishLuchtModelstatus")&&!runtime.includes("uiBasisLucht"));
assert.equal(api.luchtdrukTekst,undefined);
assert(!runtime.includes("uiLuchtdrukTekst")&&!runtime.includes('document.getElementById("pressub")'));
assert.equal(api.windstootTekst,undefined);
assert(!runtime.includes("uiWindstootTekst")&&!runtime.includes("uiBasisMeters")&&!runtime.includes('piek("wind_gusts_10m")')&&!runtime.includes('zetTekst("gustsub"'));
assert(runtime.includes("UI-polish wrapt meters() daarom niet meer."));
assert(apply.includes('require("./wind-gust-copy-owner.js")')&&apply.includes("GUST_PRODUCTIE")&&apply.includes("HELPER_PRODUCTIE"));

assert.equal(api.zonurenWoord,undefined,"UI-polish mag geen zonurencopyhelper meer exporteren");
for(const oud of ["uiZonurenWoord","uiBasisZonurenTegel","zonurenTegel=function","day.sunshine_duration","day.sunrise","day.sunset"])
  assert(!runtime.includes(oud),"UI-polish bezit nog zonurenlogica: "+oud);
assert(runtime.includes("UI-polish wrapt zonurenTegel() daarom niet meer."));
assert(apply.includes('require("./sunshine-copy-owner.js")')&&apply.includes("ZONUREN_PRODUCTIE")&&apply.includes("ZON_HELPER_PRODUCTIE"));

assert(!runtime.includes("uiPolishRegenperiodeKansen")&&!runtime.includes("uiPolishRegenperiodeDaglabel")&&!runtime.includes("data-ui-rain-period-probability"));
assert(runtime.includes("/* Regenperiodepresentatie wordt volledig beheerd door Q4. */"));
assert(!apply.includes("VEROUDE_REGEN_START")&&!apply.includes("runtime=runtime.slice"));
assert(apply.includes("Verouderde UI-polish regenperiode-owner staat weer in de bronruntime"));
assert(runtime.includes('bereik.textContent="Bereik"'));
assert(runtime.includes("Voor deze locatie kunnen we geen officiële weerwaarschuwingen tonen."));
assert(runtime.includes("Officiële weerwaarschuwingen konden tijdelijk niet worden opgehaald."));
assert(!runtime.includes("Geen officiële weerwaarschuwingen voor deze locatie."));
assert(!runtime.includes('data-ui-warning-loading="1"'));
assert(!runtime.includes("Officiële weerwaarschuwingen controleren…"));
assert(runtime.includes("De base-build waarschuwingrenderer bezit loading en de expliciete lege"));
assert(apply.includes('require("./warning-render-state.js")')&&apply.includes("START_PRODUCTIE")&&apply.includes("EIND_PRODUCTIE"));
assert(!apply.includes("WAARSCHUWING_START")&&!apply.includes("WAARSCHUWING_EIND"));
assert(apply.includes('const APP_OPEN=\'<div id="app" style="display:none">\''));
assert(apply.includes('html=html.replace(APP_OPEN,\'<main id="app" style="display:none">\')'));
assert(apply.includes('footer a,footer details summary{display:inline-flex;align-items:center;min-height:44px'));
assert(apply.includes('if((html.match(/<main id="app" style="display:none">/g)||[]).length!==1)'));
console.log("UI-polish regressiecontract groen: bestaande presentatieregels plus unieke UV-, pollen-, luchtdruk-, windstoot- en zonurenownership bewaakt.");